/* member.js */
export const members = [
  { id: 1, name: '강효정', github: 'ahyohyo', englishName: 'Kang Hyojeong' },
  { id: 2, name: '공기훈', github: 'a1rhun', englishName: 'Gong Gihun' },
  { id: 3, name: '금고은', github: 'eunigo', englishName: 'KEUM GOEUN' },
  { id: 4, name: '김민아', github: 'kimminna', englishName: 'KIM MINA' },
  { id: 5, name: '김유민', github: 'yumin-kim2', englishName: 'Kim Yu Min' },
  {
    id: 6,
    name: '김종현',
    github: 'KimJongHyun2',
    englishName: 'Kim JongHyun',
  },
  { id: 7, name: '김지민', github: 'zzos0014', englishName: 'KIM JIMIN' },
  { id: 8, name: '김지영', github: '2516391', englishName: 'KIM JEEYOUNG' },
  { id: 9, name: '김희수', github: 'kimxeesoo', englishName: 'KIM HEE SOO' },
  { id: 10, name: '남주형', github: 'Juhyung03', englishName: 'NAM JUHYUNG' },
  { id: 11, name: '박시은', github: 'nueisx', englishName: 'Park Sieun' },
  { id: 12, name: '박우찬', github: 'pwc2002', englishName: 'PART WOOCHAN' },
  { id: 13, name: '손승현', github: 'son0131', englishName: 'Son Seunghyun' },
  { id: 14, name: '심민식', github: 'minsik1014', englishName: 'SIM MINSIK' },
  { id: 15, name: '오세영', github: 'comehere43', englishName: 'OH SEYOUNG' },
  { id: 16, name: '이보성', github: 'bosung0505', englishName: 'Lee Boseong' },
  { id: 17, name: '이지연', github: 'jiyeoniii', englishName: 'LEE JIYEON' },
  { id: 18, name: '이채원', github: 'chaewon41', englishName: 'LEE CHAEWON' },
  { id: 19, name: '이해니', github: 'haeni82', englishName: 'LEE HAENI' },
  { id: 20, name: '장준호', github: 'Junho73', englishName: 'Jang Junho' },
  { id: 21, name: '장희진', github: 'lodestar123', englishName: 'JANG HUIJIN' },
  { id: 22, name: '조영찬', github: 'ychany', englishName: 'JO YEONGCHAN' },
  { id: 23, name: '조예슬', github: 'joyrii', englishName: 'Jo Yeseul' },
  {
    id: 24,
    name: '조현영',
    github: 'hycho8901@gmail.com',
    englishName: 'HyounYoung Cho',
  },
  { id: 25, name: '최예빈', github: 'YeBeenChoi', englishName: 'Choi Yebeen' },
  { id: 26, name: '최효비', github: 'Hyobee02', englishName: 'Choi HyoBee' },
  { id: 27, name: '한혜원', github: 'gksgPDnjs', englishName: 'Han Hyewon' },
  { id: 28, name: '황유림', github: 'yurimidaH', englishName: 'Hwang Yurim' },
];
